-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Delay is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    t1_s_V : IN STD_LOGIC_VECTOR (47 downto 0);
    t2_s_V : IN STD_LOGIC_VECTOR (47 downto 0);
    t3_s_V : IN STD_LOGIC_VECTOR (47 downto 0);
    t4_s_V : IN STD_LOGIC_VECTOR (47 downto 0);
    t1 : IN STD_LOGIC_VECTOR (31 downto 0);
    t2 : IN STD_LOGIC_VECTOR (31 downto 0);
    t3 : IN STD_LOGIC_VECTOR (31 downto 0);
    t4 : IN STD_LOGIC_VECTOR (31 downto 0);
    rv_V : IN STD_LOGIC_VECTOR (11 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Delay is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Delay,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-i,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.947000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=10,HLS_SYN_FF=76,HLS_SYN_LUT=464,HLS_VERSION=2018_3}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3B9ACA00 : STD_LOGIC_VECTOR (31 downto 0) := "00111011100110101100101000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal rv_V_read_reg_261 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_V_fu_138_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_V_reg_266 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_1_fu_166_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_1_reg_271 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal t4_s_V_assign_fu_116_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_fu_122_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal t4_assign_fu_132_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_126_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_144_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_1_fu_150_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal t3_assign_fu_160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_154_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_fu_178_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_fu_178_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal r_V_2_fu_178_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal rhs_V_fu_188_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal lhs_V_fu_184_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal rhs_V_1_cast_fu_195_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal ret_V_fu_199_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal p_Result_2_fu_213_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_229_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_239_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_205_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_245_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_fu_178_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal r_V_2_fu_178_p10 : STD_LOGIC_VECTOR (43 downto 0);


begin



    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                p_Val2_1_reg_271 <= p_Val2_1_fu_166_p2;
                rv_V_read_reg_261 <= rv_V;
                tmp_V_reg_266 <= tmp_V_fu_138_p2;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        tmp_5_fu_245_p3 when (p_Result_s_fu_205_p3(0) = '1') else 
        tmp_3_fu_229_p4;
    lhs_V_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_2_fu_178_p2),45));
    p_Result_2_fu_213_p4 <= ret_V_fu_199_p2(8 downto 1);
    p_Result_s_fu_205_p3 <= ret_V_fu_199_p2(44 downto 44);
    p_Val2_1_fu_166_p2 <= std_logic_vector(unsigned(t3_assign_fu_160_p2) + unsigned(tmp_6_fu_154_p2));
    r_V_2_fu_178_p0 <= r_V_2_fu_178_p00(32 - 1 downto 0);
    r_V_2_fu_178_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_reg_266),44));
    r_V_2_fu_178_p1 <= r_V_2_fu_178_p10(12 - 1 downto 0);
    r_V_2_fu_178_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rv_V_read_reg_261),44));
    r_V_2_fu_178_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_2_fu_178_p0) * unsigned(r_V_2_fu_178_p1), 44));
    ret_V_fu_199_p2 <= std_logic_vector(unsigned(lhs_V_fu_184_p1) - unsigned(rhs_V_1_cast_fu_195_p1));
    rhs_V_1_cast_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rhs_V_fu_188_p3),45));
    rhs_V_fu_188_p3 <= (p_Val2_1_reg_271 & ap_const_lv8_0);
    t3_assign_fu_160_p2 <= std_logic_vector(unsigned(t3) - unsigned(t2));
    t4_assign_fu_132_p2 <= std_logic_vector(unsigned(t4) - unsigned(t1));
    t4_s_V_assign_fu_116_p2 <= std_logic_vector(unsigned(t4_s_V) - unsigned(t1_s_V));
    tmp_1_fu_150_p1 <= tmp_4_fu_144_p2(32 - 1 downto 0);
    tmp_2_fu_126_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv32_3B9ACA00) * signed(tmp_fu_122_p1))), 32));
    tmp_3_fu_229_p4 <= ret_V_fu_199_p2(40 downto 9);
    tmp_4_fu_144_p2 <= std_logic_vector(unsigned(t3_s_V) - unsigned(t2_s_V));
    tmp_5_fu_245_p3 <= 
        tmp_3_fu_229_p4 when (tmp_s_fu_223_p2(0) = '1') else 
        tmp_8_fu_239_p2;
    tmp_6_fu_154_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv32_3B9ACA00) * signed(tmp_1_fu_150_p1))), 32));
    tmp_8_fu_239_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(tmp_3_fu_229_p4));
    tmp_V_fu_138_p2 <= std_logic_vector(unsigned(t4_assign_fu_132_p2) + unsigned(tmp_2_fu_126_p2));
    tmp_fu_122_p1 <= t4_s_V_assign_fu_116_p2(32 - 1 downto 0);
    tmp_s_fu_223_p2 <= "1" when (p_Result_2_fu_213_p4 = ap_const_lv8_0) else "0";
end behav;
